export const ListaMenu = [
    {
        id:1,
        url:'/home',
        title:'Inicio',
        icon:'home',
        sub:false
    },
    {
        id:98,
        url:'/contabilidad',
        title:'Contabilidad',
        icon:'calculate',
        sub:false
    },
    {
        id:6,
        url:'/memo',
        title:'Memos',
        icon:'question_answer',
        sub:false
    },
    {
        id:78,
        url:'#',
        title:'Comercial',
        icon:'sell',
        sub:true,
        open:false,
        submenu:[
            {
                id:9,
                title:'Nuevo pedido',
                url:'/pedidos?open=nuevo',
                icon:'receipt'
            },
            {
                id:1,
                title:'Pedidos',
                url:'/pedidos/lista',
                icon:'receipt_long'
            },
            {
                id:41,
                title:'Recibos pedido',
                url:'/recibospedidos',
                icon:'article'
            },
            {
                id:42,
                title:'Nueva factura',
                url:'/facturas/add',
                icon:'credit_card'
            },
            {
                id:42,
                title:'Facturas',
                url:'/facturas/lista',
                icon:'receipt'
            },
            
            
        ]
    },
    {
        id:71,
        url:'#',
        title:'Stock',
        icon:'inventory_2',
        sub:true,
        open:false,
        submenu:[
            {
                id:41,
                title:'Categorias',
                url:'/categorias',
                icon:'category'
            },
            {
                id:41,
                title:'Productos',
                url:'/productos',
                icon:'shopping_bag'
            },
            {
                id:456,
                title:'Inventario',
                url:'/inventario',
                icon:'inventory'
            },
            {
                id:42,
                title:'Depositos',
                url:'/depositos',
                icon:'store'
            }
        ]
    }, 
    {
        id:87,
        url:'#',
        title:'Reportes',
        icon:'summarize',
        sub:true,
        open:false,
        submenu:[
            {
                id:41,
                title:'Generales',
                url:'/reportes/generales',
                icon:'tabler:report-analytics'
            },
            {
                id:42,
                title:'Productos',
                url:'/reportes/productos',
                icon:'ep:sell'
            },
            {
                id:43,
                title:'Ventas',
                url:'/reportes/ventas',
                icon:'mdi:report-line'
            },
            {
                id:43,
                title:'Gráficos',
                url:'/reportes/graficos',
                icon:'mdi:report-bar'
            }
        ]
    }, 
    {
        id:7818,
        url:'#',
        title:'RRHH',
        icon:'people_alt',
        sub:true,
        open:false,
        submenu:[
            {
                id:41,
                title:'Empleados',
                url:'/empleados',
                icon:'perm_contact_calendar'
            }
        ]
    },
    {
        id:7,
        url:'#',
        title:'Financiero',
        icon:'account_balance_wallet',
        sub:true,
        open:false,
        submenu:[
            {
                id:41,
                title:'Ventas',
                url:'/ventas',
                icon:'ic:twotone-sell'
            },
            {
                id:42,
                title:'A cobrar',
                url:'/cuentas/cobrar',
                icon:'tabler:pig-money'
            },
            {
                id:43,
                title:'A pagar',
                url:'/cuentas/pagar',
                icon:'ic:baseline-money'
            }
        ]
    }, 
    {
        id:788,
        url:'#',
        title:'Admin...',
        icon:'settings',
        sub:true,
        open:false,
        submenu:[
            {
                id:31,
                url:'/empresa',
                title:'Empresa',
                icon:'store_mall_directory',
                sub:false
            },
            {
                id:3,
                url:'/clientes',
                title:'Clientes',
                icon:'groups',
                sub:false
            },
            {
                id:3,
                url:'/descuentos',
                title:'Descuentos',
                icon:'price_check',
                sub:false
            },
            {
                id:41,
                title:'Proveedores',
                url:'/proveedores',
                icon:'local_shipping'
            },
            {
                id:15,
                url:'/usuarios',
                title:'Usuarios',
                icon:'assignment_ind',
                sub:false
            },
        ]
    },
    //

    
    
    
]