export const ListaMenu = [
    {
        id:1,
        url:'/home',
        title:'Inicio',
        icon:'fluent-mdl2:home',
        sub:false
    },
    {
        id:98,
        url:'/contabilidad',
        title:'Contabilidad',
        icon:'ic:twotone-menu-book',
        sub:false
    },
    {
        id:6,
        url:'/memo',
        title:'Memos',
        icon:'ic:twotone-sticky-note-2',
        sub:false
    },
    {
        id:78,
        url:'#',
        title:'Comercial',
        icon:'carbon:store',
        sub:true,
        open:false,
        submenu:[
            {
                id:41,
                title:'Pedidos',
                url:'/pedidos',
                icon:'ic:baseline-receipt-long'
            },
            {
                id:42,
                title:'Vender',
                url:'/vender',
                icon:'ion:cash-outline'
            },
        ]
    },
    {
        id:71,
        url:'#',
        title:'Stock',
        icon:'fluent-mdl2:product-release',
        sub:true,
        open:false,
        submenu:[
            {
                id:41,
                title:'Categorias',
                url:'/categorias',
                icon:'ic:twotone-category'
            },
            {
                id:41,
                title:'Productos',
                url:'/productos',
                icon:'fluent-mdl2:product-variant'
            },
            {
                id:4521,
                title:'Mov. Stock',
                url:'/movstock',
                icon:'ic:twotone-move-down'
            },
            {
                id:456,
                title:'Inventario',
                url:'/inventario',
                icon:'ic:twotone-inventory'
            },
            {
                id:42,
                title:'Depositos',
                url:'/depositos',
                icon:'ic:twotone-local-convenience-store'
            }
        ]
    }, 
    {
        id:87,
        url:'#',
        title:'Reportes',
        icon:'octicon:graph-24',
        sub:true,
        open:false,
        submenu:[
            {
                id:41,
                title:'Generales',
                url:'/reportes/generales',
                icon:'tabler:report-analytics'
            },
            {
                id:42,
                title:'Productos',
                url:'/reportes/productos',
                icon:'ep:sell'
            },
            {
                id:43,
                title:'Ventas',
                url:'/reportes/ventas',
                icon:'mdi:report-line'
            },
            {
                id:43,
                title:'Gráficos',
                url:'/reportes/graficos',
                icon:'mdi:report-bar'
            }
        ]
    }, 
    {
        id:7818,
        url:'#',
        title:'RRHH',
        icon:'mdi:human-capacity-increase',
        sub:true,
        open:false,
        submenu:[
            {
                id:41,
                title:'Empleados',
                url:'/empleados',
                icon:'clarity:employee-line'
            }
        ]
    },
    {
        id:7,
        url:'#',
        title:'Financiero',
        icon:'fluent-mdl2:money',
        sub:true,
        open:false,
        submenu:[
            {
                id:41,
                title:'Ventas',
                url:'/ventas',
                icon:'ic:twotone-sell'
            },
            {
                id:42,
                title:'A cobrar',
                url:'/cuentas/cobrar',
                icon:'tabler:pig-money'
            },
            {
                id:43,
                title:'A pagar',
                url:'/cuentas/pagar',
                icon:'ic:baseline-money'
            }
        ]
    }, 
    {
        id:788,
        url:'#',
        title:'Admin...',
        icon:'pajamas:admin',
        sub:true,
        open:false,
        submenu:[
            {
                id:3,
                url:'/clientes',
                title:'Clientes',
                icon:'ic:twotone-people',
                sub:false
            },
            {
                id:41,
                title:'Proveedores',
                url:'/proveedores',
                icon:'fluent:vehicle-truck-cube-20-regular'
            },
            {
                id:5,
                url:'/usuarios',
                title:'Usuarios',
                icon:'carbon:credentials',
                sub:false
            },
        ]
    },
    //

    
    
    
]